---

- name: Create jenkins configuration for RedHat
  file: path=/etc/sysconfig/jenkins state=touch
  when: ansible_os_family == "RedHat"

- name: Configure Jenkins Port for RedHat
  lineinfile: dest=/etc/sysconfig/jenkins regexp=^JENKINS_PORT= line=JENKINS_PORT={{port}}
  register: config_changed
  when: ansible_os_family == "RedHat"

- name: Configure Jenkins Port for Debian
  lineinfile: dest=/etc/default/jenkins regexp=^HTTP_PORT= line=HTTP_PORT={{port}}
  register: config_changed
  when: ansible_os_family == "Debian"

- name: Restart jenkins now
  service: name=jenkins state=restarted
  when: config_changed.changed

- name: Configure Jenkins Prefix for RedHat
  when: prefix is defined and ansible_os_family == "RedHat"
  lineinfile: dest=/etc/sysconfig/jenkins regexp=^PREFIX= line=PREFIX={{prefix}}

- name: Configure Jenkins Prefix for Debian
  when: prefix is defined and ansible_os_family == "Debian"
  lineinfile: dest=/etc/default/jenkins regexp=^PREFIX= line=PREFIX={{prefix}}

- name: Configure Jenkins Listen for RedHat
  when: listen is defined and ansible_os_family == "RedHat"
  lineinfile: dest=/etc/sysconfig/jenkins regexp=^HTTP_HOST= line=HTTP_HOST={{listen}} insertbefore=JENKINS_ARGS

- name: Configure Jenkins Listen for Debian
  when: listen is defined and ansible_os_family == "Debian"
  lineinfile: dest=/etc/default/jenkins regexp=^HTTP_HOST= line=HTTP_HOST={{listen}} insertbefore=JENKINS_ARGS

- name: Configure Jenkins args for RedHat
  when: listen is defined and ansible_os_family == "RedHat"
  lineinfile:
    dest: /etc/sysconfig/jenkins
    regexp: ^JENKINS_ARGS=
    line: JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --httpListenAddress=$HTTP_HOST --ajp13Port=$AJP_PORT"

- name: Configure Jenkins args for Debian
  when: listen is defined and ansible_os_family == "Debian"
  lineinfile:
    dest: /etc/default/jenkins
    regexp: ^JENKINS_ARGS=
    line: JENKINS_ARGS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --httpListenAddress=$HTTP_HOST --ajp13Port=$AJP_PORT"

- name: Configure Jenkins E-mail
  when: email is defined
  template: src=hudson.tasks.Mailer.xml.j2 dest={{ jenkins_lib }}/hudson.tasks.Mailer.xml owner=jenkins group=jenkins mode=0644
